### ISSUE TITLE
Sorry, just a question

### ISSUE THREAD

**Issue by andye2004** [holixon/axon-testing#176]
This library looks interesting, but I was wondering, does it work with axon-spring-boot?

Thanks, Andy.

**Comment by jangalinski** [comment]
Hi Andy ... currently we have 2 modules here: enhancement for the build-in axon-testfixtures and a toolset for upcater testing.
Both address the "unit" level of the test-pyramid.

There is no special support for spring boot. If you want to do a spring boot integration test of your axon-app, you basically will setup a custom spring-test context and just run your app ... the axon-server testcontainer can be a useful addition to that setup. But there is nothing particularly designed for spring boot testing here.

BTW: feel free to use the https://github.com/holixon/axon-testing/discussions section to continue.

regards
Jan
